coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 90%

  ignore:
    - "tests/"
    - "benchmarks/"
    - "docs/"
    - "examples/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
